// <auto-generated />
using Livraria.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Livraria.Context.Migrations
{
    [DbContext(typeof(ContextoDeDados))]
    [Migration("20210222220920_BancoInicial")]
    partial class BancoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Livraria.Domain.Livros.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Setor")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("Livraria.Domain.Livros.Tema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Valor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Temas");
                });

            modelBuilder.Entity("Livraria.Domain.ManyToMany.AutorLivro", b =>
                {
                    b.Property<int>("IdLivro")
                        .HasColumnType("integer");

                    b.Property<int>("IdAutor")
                        .HasColumnType("integer");

                    b.HasKey("IdLivro", "IdAutor");

                    b.HasIndex("IdAutor");

                    b.ToTable("AutoresLivros");
                });

            modelBuilder.Entity("Livraria.Domain.ManyToMany.LivroTema", b =>
                {
                    b.Property<int>("IdLivro")
                        .HasColumnType("integer");

                    b.Property<int>("IdTema")
                        .HasColumnType("integer");

                    b.HasKey("IdLivro", "IdTema");

                    b.HasIndex("IdTema");

                    b.ToTable("LivrosTemas");
                });

            modelBuilder.Entity("Livraria.Domain.Pessoas.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Administrador"
                        });
                });

            modelBuilder.Entity("Livraria.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("IdPessoa")
                        .HasColumnType("integer");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<int>("Permissao")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdPessoa");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "teste@123",
                            IdPessoa = 1,
                            Login = "admin",
                            Permissao = 1,
                            Senha = "gqefEbSstSpkLvfjOd/OSqkv9l7S56twLXmNvhDsoLg="
                        });
                });

            modelBuilder.Entity("Livraria.Domain.ManyToMany.AutorLivro", b =>
                {
                    b.HasOne("Livraria.Domain.Pessoas.Pessoa", "Autor")
                        .WithMany("Livros")
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Livraria.Domain.Livros.Livro", "Livro")
                        .WithMany("Autores")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("Livraria.Domain.ManyToMany.LivroTema", b =>
                {
                    b.HasOne("Livraria.Domain.Livros.Livro", "Livro")
                        .WithMany("Temas")
                        .HasForeignKey("IdLivro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Livraria.Domain.Livros.Tema", "Tema")
                        .WithMany("Livros")
                        .HasForeignKey("IdTema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("Livraria.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("Livraria.Domain.Pessoas.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("IdPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Livraria.Domain.Livros.Livro", b =>
                {
                    b.Navigation("Autores");

                    b.Navigation("Temas");
                });

            modelBuilder.Entity("Livraria.Domain.Livros.Tema", b =>
                {
                    b.Navigation("Livros");
                });

            modelBuilder.Entity("Livraria.Domain.Pessoas.Pessoa", b =>
                {
                    b.Navigation("Livros");
                });
#pragma warning restore 612, 618
        }
    }
}
